### ISSUE TITLE
Update HTTP response status codes in firewall

### ISSUE THREAD

**Issue by summercms** [summercms/sc-security-module#554]
### Enhancement idea

- [ ] Update HTTP response status codes in firewall.
- [ ] Update `Request` system.
- [ ] Update `Response` system.
- [ ] Update labelling system.
- [ ] Update Filters.

**Comment by summercms** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
https://httpstatus.io/http-status-codes

**Comment by summercms** [comment]
Flag and catch mixed content
or
Missing content

**Comment by summercms** [comment]
https://laravel.com/api/6.x/Illuminate/Http/Response.html#method_status

**Comment by summercms** [comment]
empty os

**Comment by summercms** [comment]
referral traffic

**Comment by summercms** [comment]
```css
.columns__separator {
    background: #cdcdcd;
    background: -webkit-gradient(linear,left top,right top,color-stop(0,#cdcdcd),color-stop(5%,#ececec),color-stop(100%,#fefefe));
    background: -webkit-linear-gradient(left,#cdcdcd 0,#ececec 5%,#fefefe 100%);
    background: -o-linear-gradient(left,#cdcdcd 0,#ececec 5%,#fefefe 100%);
    background: -webkit-gradient(linear,left top,right top,from(#cdcdcd),color-stop(5%,#ececec),to(#fefefe));
    background: linear-gradient(to right,#cdcdcd 0,#ececec 5%,#fefefe 100%);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#cdcdcd', endColorstr='#fefefe', GradientType=1);
    height: 100%;
    width: 2em;
    position: absolute;
    left: 66.66%;
    top: 0;
    padding-bottom: 3em;
}
```
